//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTable
{
    using System;
    using System.IO;
    using System.Collections.Generic;
    using Common;
    
    
    public class TableManager : Singleton<TableManager>
    {
        
        public EnemyTable EnemyTableContainer { get; private set; } = new EnemyTable();
        
        public StageTable StageTableContainer { get; private set; } = new StageTable();
        
        public void Initialize()
        {
            EnemyTableContainer.LoadTable();
            StageTableContainer.LoadTable();
        }
    }
}
